name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  # Lint and type check
  lint:
    name: Lint and Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint --if-present

      - name: Type check
        run: npm run type-check --if-present

  # Build SDK
  build-sdk:
    name: Build SDK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build SDK
        run: |
          cd packages/fhevm-sdk
          npm run build

      - name: Check build artifacts
        run: |
          cd packages/fhevm-sdk
          ls -la dist/

  # Test SDK
  test-sdk:
    name: Test SDK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: |
          cd packages/fhevm-sdk
          npm test --if-present

  # Build Next.js Showcase
  build-nextjs-showcase:
    name: Build Next.js Showcase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build SDK first
        run: |
          cd packages/fhevm-sdk
          npm run build

      - name: Build Next.js Showcase
        run: |
          cd examples/nextjs-showcase
          npm run build

  # Build Traffic Analytics
  build-traffic-analytics:
    name: Build Traffic Analytics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build SDK first
        run: |
          cd packages/fhevm-sdk
          npm run build

      - name: Build Traffic Analytics
        run: |
          cd examples/traffic-analytics
          npm run build

  # Check bundle size
  bundle-size:
    name: Check Bundle Size
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build SDK
        run: |
          cd packages/fhevm-sdk
          npm run build

      - name: Check SDK bundle size
        run: |
          cd packages/fhevm-sdk
          du -sh dist/
          ls -lh dist/*.js

  # All checks passed
  all-checks-passed:
    name: All Checks Passed
    runs-on: ubuntu-latest
    needs: [lint, build-sdk, test-sdk, build-nextjs-showcase, build-traffic-analytics, bundle-size]
    steps:
      - name: All checks passed
        run: echo "✅ All CI checks passed successfully!"
